out_dir: tests/mix-all-fullgraph-extra-v2
num_workers: 8
num_threads: 16
prefetch_factor: 4
debug: false
wandb:
  use: true
  entity: togglec
  project: tpu-graph-v2
dataset:
  name: MixTPUGraphsNpz
  format: PyG-MixTPUGraphsNpz
  task: graph
  task_type: ranking
  transductive: False
  dir: datasets/
  source: xla+nlp
  search: default+random
  num_sample_config: 48
  eval_num_sample_config: 96
  input_feat_key: op_feat_enc_i
  cache_in_memory: false
  khop:
    use: true
    hops: 2
    bidirect: true
  config_sampler: IntervalSampler
  extra_cfg_feat_keys: ["extra_feat", "extra_read_ops_feat"]
  extra_cfg_feat_dims: 316

train:
  mode: custom_tpu
  batch_size: 2
  eval_period: 1
  ckpt_period: 2
  sampler: full_batch
  auto_resume: true
  adap_margin: false
  gst:
    sample_full_graph: true
model:
  type: custom_tpu_gnn
  loss_fun: hinge
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 2
  dim_inner: 256
  layer_type: sageconvlayer
  stage_type: skipsum
  batchnorm: False
  act: prelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
  enc_config: true
  freeze_body: false
  dim_feat_enc: 192
optim:
  optimizer: adam
  base_lr: 0.0001
  max_epoch: 100
  batch_accumulation: 2
share:
  dim_in: 286
device: cuda
seed: 20
# model_ckpt: tests/mix-random-fullgraph-extra-v2/random-full-extra-v2-gcp/20/best-3.ckpt