# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tuning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import hlo_pb2 as hlo__pb2
from . import xla_data_pb2 as xla__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tuning.proto',
  package='tpu_graphs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ctuning.proto\x12\ntpu_graphs\x1a\thlo.proto\x1a\x0exla_data.proto\";\n\nTuningData\x12-\n\x07modules\x18\x01 \x03(\x0b\x32\x1c.tpu_graphs.ModuleTuningData\"\x93\x01\n\x10ModuleTuningData\x12#\n\x06module\x18\x01 \x01(\x0b\x32\x13.xla.HloModuleProto\x12\x13\n\x0b\x66ingerprint\x18\x02 \x01(\x04\x12\'\n\x04runs\x18\x03 \x03(\x0b\x32\x19.tpu_graphs.ConfigProfile\x12\x1c\n\x14\x63onfig_index_to_node\x18\x04 \x03(\x04\"\xc8\x01\n\rConfigProfile\x12,\n\top_config\x18\x01 \x01(\x0b\x32\x17.tpu_graphs.HloOpConfigH\x00\x12\x34\n\rmodule_config\x18\x02 \x01(\x0b\x32\x1b.tpu_graphs.HloModuleConfigH\x00\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\x12&\n\x07profile\x18\x04 \x01(\x0b\x32\x15.xla.ExecutionProfile\x12\x12\n\nis_default\x18\x05 \x01(\x08\x42\x08\n\x06\x63onfig\"C\n\x0bHloOpConfig\x12\x34\n\x10tile_size_config\x18\x01 \x01(\x0b\x32\x1a.tpu_graphs.TileSizeConfig\"n\n\x0eTileSizeConfig\x12\x15\n\rkernel_bounds\x18\x01 \x03(\x03\x12\x15\n\routput_bounds\x18\x02 \x03(\x03\x12\x14\n\x0cinput_bounds\x18\x03 \x03(\x03\x12\x18\n\x10iteration_bounds\x18\x04 \x03(\x03\"B\n\x0fHloModuleConfig\x12/\n\rlayout_config\x18\x01 \x01(\x0b\x32\x18.tpu_graphs.LayoutConfig\"\xd0\x01\n\x0cLayoutConfig\x12\x38\n\x05nodes\x18\x01 \x03(\x0b\x32).tpu_graphs.LayoutConfig.NodeLayoutConfig\x1a\x85\x01\n\x10NodeLayoutConfig\x12M\n\x07tensors\x18\x01 \x03(\x0b\x32<.tpu_graphs.LayoutConfig.NodeLayoutConfig.TensorLayoutConfig\x1a\"\n\x12TensorLayoutConfig\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x62\x06proto3')
  ,
  dependencies=[hlo__pb2.DESCRIPTOR,xla__data__pb2.DESCRIPTOR,])




_TUNINGDATA = _descriptor.Descriptor(
  name='TuningData',
  full_name='tpu_graphs.TuningData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modules', full_name='tpu_graphs.TuningData.modules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=114,
)


_MODULETUNINGDATA = _descriptor.Descriptor(
  name='ModuleTuningData',
  full_name='tpu_graphs.ModuleTuningData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='tpu_graphs.ModuleTuningData.module', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='tpu_graphs.ModuleTuningData.fingerprint', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runs', full_name='tpu_graphs.ModuleTuningData.runs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config_index_to_node', full_name='tpu_graphs.ModuleTuningData.config_index_to_node', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=264,
)


_CONFIGPROFILE = _descriptor.Descriptor(
  name='ConfigProfile',
  full_name='tpu_graphs.ConfigProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_config', full_name='tpu_graphs.ConfigProfile.op_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_config', full_name='tpu_graphs.ConfigProfile.module_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='tpu_graphs.ConfigProfile.error', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='tpu_graphs.ConfigProfile.profile', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_default', full_name='tpu_graphs.ConfigProfile.is_default', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='config', full_name='tpu_graphs.ConfigProfile.config',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=267,
  serialized_end=467,
)


_HLOOPCONFIG = _descriptor.Descriptor(
  name='HloOpConfig',
  full_name='tpu_graphs.HloOpConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tile_size_config', full_name='tpu_graphs.HloOpConfig.tile_size_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=536,
)


_TILESIZECONFIG = _descriptor.Descriptor(
  name='TileSizeConfig',
  full_name='tpu_graphs.TileSizeConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kernel_bounds', full_name='tpu_graphs.TileSizeConfig.kernel_bounds', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_bounds', full_name='tpu_graphs.TileSizeConfig.output_bounds', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_bounds', full_name='tpu_graphs.TileSizeConfig.input_bounds', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iteration_bounds', full_name='tpu_graphs.TileSizeConfig.iteration_bounds', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=648,
)


_HLOMODULECONFIG = _descriptor.Descriptor(
  name='HloModuleConfig',
  full_name='tpu_graphs.HloModuleConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout_config', full_name='tpu_graphs.HloModuleConfig.layout_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=650,
  serialized_end=716,
)


_LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG = _descriptor.Descriptor(
  name='TensorLayoutConfig',
  full_name='tpu_graphs.LayoutConfig.NodeLayoutConfig.TensorLayoutConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dims', full_name='tpu_graphs.LayoutConfig.NodeLayoutConfig.TensorLayoutConfig.dims', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=893,
  serialized_end=927,
)

_LAYOUTCONFIG_NODELAYOUTCONFIG = _descriptor.Descriptor(
  name='NodeLayoutConfig',
  full_name='tpu_graphs.LayoutConfig.NodeLayoutConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensors', full_name='tpu_graphs.LayoutConfig.NodeLayoutConfig.tensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=794,
  serialized_end=927,
)

_LAYOUTCONFIG = _descriptor.Descriptor(
  name='LayoutConfig',
  full_name='tpu_graphs.LayoutConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='tpu_graphs.LayoutConfig.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LAYOUTCONFIG_NODELAYOUTCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=927,
)

_TUNINGDATA.fields_by_name['modules'].message_type = _MODULETUNINGDATA
_MODULETUNINGDATA.fields_by_name['module'].message_type = hlo__pb2._HLOMODULEPROTO
_MODULETUNINGDATA.fields_by_name['runs'].message_type = _CONFIGPROFILE
_CONFIGPROFILE.fields_by_name['op_config'].message_type = _HLOOPCONFIG
_CONFIGPROFILE.fields_by_name['module_config'].message_type = _HLOMODULECONFIG
_CONFIGPROFILE.fields_by_name['profile'].message_type = xla__data__pb2._EXECUTIONPROFILE
_CONFIGPROFILE.oneofs_by_name['config'].fields.append(
  _CONFIGPROFILE.fields_by_name['op_config'])
_CONFIGPROFILE.fields_by_name['op_config'].containing_oneof = _CONFIGPROFILE.oneofs_by_name['config']
_CONFIGPROFILE.oneofs_by_name['config'].fields.append(
  _CONFIGPROFILE.fields_by_name['module_config'])
_CONFIGPROFILE.fields_by_name['module_config'].containing_oneof = _CONFIGPROFILE.oneofs_by_name['config']
_HLOOPCONFIG.fields_by_name['tile_size_config'].message_type = _TILESIZECONFIG
_HLOMODULECONFIG.fields_by_name['layout_config'].message_type = _LAYOUTCONFIG
_LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG.containing_type = _LAYOUTCONFIG_NODELAYOUTCONFIG
_LAYOUTCONFIG_NODELAYOUTCONFIG.fields_by_name['tensors'].message_type = _LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG
_LAYOUTCONFIG_NODELAYOUTCONFIG.containing_type = _LAYOUTCONFIG
_LAYOUTCONFIG.fields_by_name['nodes'].message_type = _LAYOUTCONFIG_NODELAYOUTCONFIG
DESCRIPTOR.message_types_by_name['TuningData'] = _TUNINGDATA
DESCRIPTOR.message_types_by_name['ModuleTuningData'] = _MODULETUNINGDATA
DESCRIPTOR.message_types_by_name['ConfigProfile'] = _CONFIGPROFILE
DESCRIPTOR.message_types_by_name['HloOpConfig'] = _HLOOPCONFIG
DESCRIPTOR.message_types_by_name['TileSizeConfig'] = _TILESIZECONFIG
DESCRIPTOR.message_types_by_name['HloModuleConfig'] = _HLOMODULECONFIG
DESCRIPTOR.message_types_by_name['LayoutConfig'] = _LAYOUTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TuningData = _reflection.GeneratedProtocolMessageType('TuningData', (_message.Message,), {
  'DESCRIPTOR' : _TUNINGDATA,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.TuningData)
  })
_sym_db.RegisterMessage(TuningData)

ModuleTuningData = _reflection.GeneratedProtocolMessageType('ModuleTuningData', (_message.Message,), {
  'DESCRIPTOR' : _MODULETUNINGDATA,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.ModuleTuningData)
  })
_sym_db.RegisterMessage(ModuleTuningData)

ConfigProfile = _reflection.GeneratedProtocolMessageType('ConfigProfile', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGPROFILE,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.ConfigProfile)
  })
_sym_db.RegisterMessage(ConfigProfile)

HloOpConfig = _reflection.GeneratedProtocolMessageType('HloOpConfig', (_message.Message,), {
  'DESCRIPTOR' : _HLOOPCONFIG,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.HloOpConfig)
  })
_sym_db.RegisterMessage(HloOpConfig)

TileSizeConfig = _reflection.GeneratedProtocolMessageType('TileSizeConfig', (_message.Message,), {
  'DESCRIPTOR' : _TILESIZECONFIG,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.TileSizeConfig)
  })
_sym_db.RegisterMessage(TileSizeConfig)

HloModuleConfig = _reflection.GeneratedProtocolMessageType('HloModuleConfig', (_message.Message,), {
  'DESCRIPTOR' : _HLOMODULECONFIG,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.HloModuleConfig)
  })
_sym_db.RegisterMessage(HloModuleConfig)

LayoutConfig = _reflection.GeneratedProtocolMessageType('LayoutConfig', (_message.Message,), {

  'NodeLayoutConfig' : _reflection.GeneratedProtocolMessageType('NodeLayoutConfig', (_message.Message,), {

    'TensorLayoutConfig' : _reflection.GeneratedProtocolMessageType('TensorLayoutConfig', (_message.Message,), {
      'DESCRIPTOR' : _LAYOUTCONFIG_NODELAYOUTCONFIG_TENSORLAYOUTCONFIG,
      '__module__' : 'tuning_pb2'
      # @@protoc_insertion_point(class_scope:tpu_graphs.LayoutConfig.NodeLayoutConfig.TensorLayoutConfig)
      })
    ,
    'DESCRIPTOR' : _LAYOUTCONFIG_NODELAYOUTCONFIG,
    '__module__' : 'tuning_pb2'
    # @@protoc_insertion_point(class_scope:tpu_graphs.LayoutConfig.NodeLayoutConfig)
    })
  ,
  'DESCRIPTOR' : _LAYOUTCONFIG,
  '__module__' : 'tuning_pb2'
  # @@protoc_insertion_point(class_scope:tpu_graphs.LayoutConfig)
  })
_sym_db.RegisterMessage(LayoutConfig)
_sym_db.RegisterMessage(LayoutConfig.NodeLayoutConfig)
_sym_db.RegisterMessage(LayoutConfig.NodeLayoutConfig.TensorLayoutConfig)


# @@protoc_insertion_point(module_scope)
