out_dir: tests/xla-random-extra-v2
num_workers: 0
num_threads: 16
debug: false
wandb:
  use: false
  entity: togglec
  project: tpu-graph-v2
dataset:
  name: TPUGraphsNpz
  format: PyG-TPUGraphsNpz
  task: graph
  task_type: ranking
  transductive: False
  dir: datasets/
  source: xla
  search: random
  num_sample_config: 16
  eval_num_sample_config: 128
  input_feat_key: op_feat_enc_i
  cache_in_memory: false
  khop:
    use: true
    hops: 2
    bidirect: true
  # config_sampler: IntervalSampler
  extra_cfg_feat_keys: ["extra_feat", "extra_read_ops_feat"]
  extra_cfg_feat_dims: 316

train:
  mode: valid-tpu
  batch_size: 4
  eval_period: 32
  ckpt_period: 100
  sampler: full_batch
  auto_resume: true
  adap_margin: true
  gst:
    sample_full_graph: false
model:
  type: custom_tpu_gnn
  loss_fun: hinge
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 2
  dim_inner: 256
  layer_type: sageconv
  stage_type: skipsum
  batchnorm: False
  act: prelu
  dropout: 0.1
  agg: mean
  normalize_adj: False
  enc_config: true
  freeze_body: false
  dim_feat_enc: 192
optim:
  optimizer: adam
  base_lr: 0.0001
  max_epoch: 1000
  batch_accumulation: 1
share:
  dim_in: 286
device: cuda
seed: 0
model_ckpt: nlp-xla-random-pin2ew0o-35.ckpt